insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Prop Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Assign');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'SETTLEM');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Chg');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Reinstatement Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Loan');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Chg Frequency');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Claim Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'ACK Signed');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Service Req-CLT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Service Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Complaint-CLT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Complaint');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Incident Rep-CLT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Incident Rep');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'FINST');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'QUEST');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'SUPPST');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'ALT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Chg Pers Details');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'NOB');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Cancel');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Health Delt');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'FATCA');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Cert');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Chg');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Chg Pers Details');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Pay/Adj/Bill');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'DOB');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'ACK Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Correspondence');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Misc');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Med Rep');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'IDENT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Cert');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Proposal Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Assignment Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Cash Benefit Withdraw');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Deletion of Insured Person(s)');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Top Up');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Reinstatement Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Policy Loan Repayment');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Policy Loan');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Maturity Payment');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Paid Up');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Partial Surrender');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Partial Withdrawal');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change Frequency of Premium Payment Mode');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Full Surrender');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Premium Holiday Reinstatement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'SA Reduction Reinstatement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Claim Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'ACK Signed');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Service Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Complaint Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Incident Report');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Financial Statement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Medical Questionnaire');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Financial Questionnaire');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Supplementary Statement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Medical Request Result');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Alteration Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change Signature');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Beneficiary Change');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Cancellation Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Health Declaration');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'FATCA');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Certificate Reprinting Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Add Rider');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change Address / Contact Information');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change of Name / ID / Nationality / DOB / Gender / Occupation / Others');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change of Payment Method');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change of UL Protection Level');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Addition of DOB');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'ACK Reissuance Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Correspondence Internal/External');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Miscellaneous');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Medical Report');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Correspondence Internal/External');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Personal ID');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Passport / Visa');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Return Policy Certificate');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'MAIN-DOC-NB');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'MAIN-DOC-PS');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'MAIN-DOC-CLAIM');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'MAIN-DOC-CC');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-SHARE-NB-PS');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-NB-PSMAINTRX');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-SHARE-NB-PS-CLAIM');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-SHARE-NB-CLAIM-PSMAINFORM');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-SHARE-PS-CLAIM');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-NB');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-PS');
insert into enumeration_constant (fact, field, value) values ('DocTrxGroup','name', 'SUPDOC-CLAIM');
insert into enumeration_constant (fact, field, value) values ('Property','name', 'PROCESSNAME');
insert into enumeration_constant (fact, field, value) values ('Property','name', 'PATHCODE');
insert into enumeration_constant (fact, field, value) values ('Action','actionType', 'TRIGGER');
insert into enumeration_constant (fact, field, value) values ('Action','actionType', 'JOIN');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'policyStatus');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'contractCreated');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'dispatchDate');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'policyAckReceived');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'policyHolderReceived');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'compliantReceived');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'incidentReceived');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'cCNeedSupport');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'nBProcessExist');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'pSProcessExist');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'claimProcessExist');
insert into enumeration_constant (fact, field, value) values ('CheckList','name', 'policyOnHold');

