insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Prop Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Assign');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'SETTLEM');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Chg');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Reinstatement Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Loan');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Chg Frequency');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Claim Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'ACK Signed');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Service Req-CLT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Service Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Complaint-CLT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Complaint');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Incident Rep-CLT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Incident Rep');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'FINST');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'QUEST');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'SUPPST');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'ALT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Chg Pers Details');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'NOB');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Cancel');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Health Delt');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'FATCA');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Cert');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Chg');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Chg Pers Details');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Pay/Adj/Bill');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'DOB');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'ACK Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Correspondence');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Misc');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Med Rep');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'IDENT');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','docTypeCd', 'Policy Cert');
