insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Proposal Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Assignment Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Cash Benefit Withdraw');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Deletion of Insured Person(s)');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Top Up');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Reinstatement Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Policy Loan Repayment');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Policy Loan');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Maturity Payment');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Paid Up');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Partial Surrender');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Partial Withdrawal');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change Frequency of Premium Payment Mode');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Full Surrender');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Premium Holiday Reinstatement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'SA Reduction Reinstatement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Claim Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'ACK Signed');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Service Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Complaint Form');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Incident Report');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Financial Statement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Medical Questionnaire');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Financial Questionnaire');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Supplementary Statement');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Medical Request Result');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Alteration Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change Signature');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Beneficiary Change');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Cancellation Req');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Health Declaration');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'FATCA');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Certificate Reprinting Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Add Rider');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change Address / Contact Information');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change of Name / ID / Nationality / DOB / Gender / Occupation / Others');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change of Payment Method');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Change of UL Protection Level');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Addition of DOB');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'ACK Reissuance Request');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Correspondence Internal/External');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Miscellaneous');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Medical Report');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Correspondence Internal/External');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Personal ID');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Passport / Visa');
insert into enumeration_constant (fact, field, value) values ('DocumentRoute','transactionTypeCd', 'Return Policy Certificate');
